### ISSUE TITLE
Todo : plan

### ISSUE THREAD

**Issue by arita37** [arita37/dsa2#180]

**Comment by migeruj** [comment]
- [ ] Redefine what is the best parameter structure to save for MLFLOW, Reason: Path files can change and it would be difficult to rollback a model or to know which hyperparameters were worked on. 
Possible solutions:
- Save the contents of the model parameters that vary or are configured (other than files) inside MLFLOW instead of saving the path.
- Save files as artifacts

- [ ] Redefine a better project structure. Reason: The more readable the project is, the more shared it will be. Including the ease of adding new features/plugins by new contributors.
Possible solution: Application with Internal packages structure
project/
│
├── bin/
│
├── docs/
│   ├── Advanced.md
│   └── Contribution_Rules.md
│
├── dsa2/
│   ├── __init__.py
│   ├── core.py
│   ├── utils.py
│   ├── features/
│   │   ├──mlflow/
│   │       |──__init__.py
│   │      ├── hello.py
│   │      └── helpers.py
│   │
│   └── pluggins/
│       ├── __init__.py
│       ├── helpers.py
│       └── utils.py
│
├── data/
│   ├──titanic/
│      └──  input.csv
│      └── output.csv
│
├── tests/
│   ├── mlflow
│   │   ├── classifier_mlflow.py
│   │   └── test_mlflow.sh
│   │
│   └── optuna/
│       ├── classifier_optuna.py
│       └── test_optuna.sh
│
├── .gitignore
├── main.py
├── LICENSE
└── README.md
- [ ] Implement in dsa2 all compatible models/ml model libraries. At least Tensorflow, Keras and PyTorch
- [ ] Track all mlflow models

List of models and libraries compatible with mlflow:
- Gluon
- H2O
- Keras
- Tensorflow
- PyTorch
- XGBoost
- Statsmodels
- Spacy
- FastAI
- SHAP
- RAPIDS

- [ ] Use docker build, test and runs for these projects. Reason: Our project is  a CLI and error replication is easier with a docker base image. Solution: Dockerize option
- [ ] Example of dsa2 usage in production environments.
- [ ] Example data repository. Reason: the example data corresponds to 90% of the package weight and will not be used in production. This would make a cleaner project. 
Possible solution: 1. Create a repository for the example data or use S3 repositorie instead 2. A script or a feature to download the data.

**Comment by arita37** [comment]
1) download data: already done in the code:

```
    dir_data_url = "https://github.com/arita37/dsa2_data/tree/main/"  #### Remote Data directory

    #### peoprocess input path
    m['path_data_preprocess'] = dir_data + f'/input/{data_name}/train/'

    #### train input path
    m['path_data_train']      = dir_data_url + f'/input/{data_name}/train/'
    m['path_data_test']       = dir_data_url + f'/input/{data_name}/test/'


https://github.com/arita37/dsa2_data
```

**Comment by arita37** [comment]
1) Docker : Not need to make the repo works (if somebody can do it in free time, am ok).
2)    Implement in dsa2 all compatible models/ml model libraries :  
           Almost done, dsa2 has template for ANY model  in source/models/


3)

**Comment by arita37** [comment]
My suggestions : 

     Improve the current logging setup (verbose == 1,2,3).

     Refactor with adding  data_url from dsa2_data repo.

     Add more documentation on source/ and different components.

     Prepare Meetup for demo.  and compare with pycaret.

**Comment by migeruj** [comment]
About how to track all mlflow models.. I consider that the user chooses his model whatever it is through model_dict. we get the class_name and map that class to which library it belongs and make the correct saving of the model with MLFLOW. I would think it would be something like this.

We can make a structure of the class_name and the library 
Example:

```python
compatible_list = {
    'sklearn': ['LGMBClassifier', "LinearSVC"],
    'statsmodels': ["Lasso-LogisticRegresion", "Logit", "Probit","OLS"]
}

##We identify what library belongs to /models
to_track = [library for library,array in list.iteritems()
            if model_dict['global_pars']['config_name'] in array]

## We choose the correct saving of the model and define if we can save it or warn the user to do it himself or add it to the contribution.
if to_track:
    model = load(model_dict['global_pars']['path_train_model']+ "/model.pkl")
    if to_track == 'sklearn':
        mlflow.sklearn.log_model(model, run_name, signature=signature,
                             registered_model_name="sklearn_"+run_name+"_"+model_class)

    if to_track == 'statsmodels':
        mlflow.statsmodels.log_model(model, run_name, signature=signature,
                             registered_model_name="sklearn_"+run_name+"_"+model_class)


else:
    log("###### The model does not seem to be compatible for logging by mlflow.  ######")
```

Is it viable in this way?

**Comment by arita37** [comment]
Thanks for good suggestion.
The idea of having open architecture is good, 
so contributors can contribute to some parts.

Your suggestion is good, we can add it.

With Optuna Visualizer, there is no need to register the model,
this is automatic from model dict.

Let me explain more dsa2 :
(We should spend 10mins in chatroom so, I can explain how dsa2 works.)

models TEMPLATE are stored in source/models/model_XXXX,py
A model template is JUST a python file with FIXED functions, class name : 

```
Model(Object)
fit()
predict()
load_dataset()
save()
load()
```

model_sklearn,py  means the template handle ANY (ANY) model 
which has sklearn template:  fit(), predict(), ....

In model_sklearn,py code, We never specify model list, THIS IS Automatic ( == Less code).
save() manages the saving part.

If a new class of framework (ie Amazon Gluon) , with specific API (<> of fit(), predict()
we can create one template.


**Why integrate MLFLOW ?**
      Re-use pre-built functionalities of MLFLOW...


**HOW TO INTEGRATE  ?** 
     It depends, there is no solution for all.... Better to discuss openly.
     For save(), we can integrate at the source/models/model_XXXX.py level.

```
         def save() ....
            if pars('save_mlflow_pars') is not None : 
                  from mlflow.sklearn_api import save
                  save(    model.model )
```

**Comment by migeruj** [comment]
So to make clear the things we need:

1. do the save() of the model at the run level of /source/models/model.py 2.
2. Make improvements in logging
3. Changes in the documentation
4. Implement the download of the missing data from dsa2_data.

Some things that come to my mind and I want to discuss:
Documentation for deploys to production and example scripts: 

- how to save the model
- how to import it
- how to run it
- model as a service
- best performance config

Why do this?
Many data scientists, statisticians and researchers do not know the best way to use the model as a service and if they do not know the right tools or the proper use of them they tend to have concurrent problems. May dsa2 allow to solve this as well.

**Comment by arita37** [comment]
Yes good.

Lets focus on :
Goal 1 :
   Deploy the model through API

And make a list of what we need.
Does mlflow can handle it ?


4) is already done.
